api:
  security:
    jwt:
      secret: 4bdc96764b1084f87155f7c02a46d13ef969c5a4522f4630685bf90777bb30e0

spring:
  application:
    name: aplicai
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
    url: jdbc:h2:file:./data/aplicai
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
  data:
    mongodb:
      uri: mongodb://sa:1234@localhost:27017/aplicai_resumes?authSource=admin
